services:
  signoz-signoz-0:
    environment:
      SIGNOZ_ALERTMANAGER_SIGNOZ_EXTERNAL__URL: ${SIGNOZ_EXTERNAL_URL:?set SIGNOZ_EXTERNAL_URL}
      SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__FROM: ${SIGNOZ_SMTP_FROM:?set SIGNOZ_SMTP_FROM}
      SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__SMARTHOST: ${SIGNOZ_SMTP_SMARTHOST:?set SIGNOZ_SMTP_SMARTHOST}
      SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__AUTH__USERNAME: ${SIGNOZ_SMTP_USERNAME:?set SIGNOZ_SMTP_USERNAME}
      SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__AUTH__PASSWORD: ${SIGNOZ_SMTP_PASSWORD:?set SIGNOZ_SMTP_PASSWORD}
