import { Effect, Schema } from "effect"
import { OpenApi } from "effect/unstable/httpapi"
import { describe, expect, it } from "vitest"

import {
  CreateEpisodeJobRequestSchema,
  EpisodeSchema,
  gatewayApi,
  generateOpenApi,
  JobReceiptSchema,
} from "./contract.js"

const validArticleId = "5af55f2e-ff0b-475c-866a-f2cff48c101d"

describe("gateway HttpApi contract", () => {
  it("generates the complete public OpenAPI 3.1 surface", () => {
    const specification = generateOpenApi()

    expect(specification.openapi).toBe("3.1.0")
    expect(specification.info).toMatchObject({
      title: "RSS News Podcast API",
      version: "1.0.0",
    })
    expect(Object.keys(specification.paths).sort()).toEqual([
      "/api/auth/state",
      "/health",
      "/v1/episode-jobs",
      "/v1/episodes",
      "/v1/episodes/{episodeId}/audio-access",
    ])
    expect(specification.paths["/health"]?.get?.operationId).toBe("health")
    expect(specification.paths["/api/auth/state"]?.get?.operationId).toBe(
      "resolveSession"
    )
    expect(
      specification.paths["/v1/episode-jobs"]?.post?.responses
    ).toHaveProperty("202")
    expect(
      specification.paths["/v1/episodes/{episodeId}/audio-access"]?.post
        ?.responses
    ).toHaveProperty("404")
  })

  it("is generated by Effect OpenApi without a handwritten document", () => {
    expect(generateOpenApi()).toEqual(OpenApi.fromApi(gatewayApi))
  })

  it("parses only valid episode job creation payloads", async () => {
    const valid = await Effect.runPromise(
      Schema.decodeUnknownEffect(CreateEpisodeJobRequestSchema)({
        trigger: "manual",
        articleIds: [validArticleId],
      })
    )

    expect(valid).toEqual({
      trigger: "manual",
      articleIds: [validArticleId],
    })

    for (const invalid of [
      { trigger: "scheduled" },
      { trigger: "manual", articleIds: [] },
      { trigger: "manual", articleIds: ["article-1"] },
      {
        trigger: "manual",
        articleIds: Array.from({ length: 21 }, () => validArticleId),
      },
    ]) {
      const exit = await Effect.runPromiseExit(
        Schema.decodeUnknownEffect(CreateEpisodeJobRequestSchema)(invalid)
      )
      expect(exit._tag).toBe("Failure")
    }
  })

  it("rejects normalized calendar dates and whitespace-only domain text", async () => {
    const invalidReceipt = await Effect.runPromiseExit(
      Schema.decodeUnknownEffect(JobReceiptSchema)({
        id: "7f52766d-3b0b-4ca9-b5e8-7bfd35dc3a80",
        status: "queued",
        createdAt: "2026-02-30T00:00:00.000Z",
        attempt: 0,
        maxAttempts: 4,
      })
    )
    const invalidEpisode = await Effect.runPromiseExit(
      Schema.decodeUnknownEffect(EpisodeSchema)({
        id: "3c4d046c-b47b-4047-a562-66ac7e74e995",
        title: "   ",
        script: "Valid script",
        sources: [
          {
            url: "https://example.com/article",
            title: "Source",
          },
        ],
        createdAt: "2026-08-12T00:00:00.000Z",
      })
    )

    expect(invalidReceipt._tag).toBe("Failure")
    expect(invalidEpisode._tag).toBe("Failure")
  })
})
