apiVersion: 1

contactPoints:
  - orgId: 1
    name: news-podcast-email
    receivers:
      - uid: news-podcast-email
        type: email
        disableResolveMessage: false
        settings:
          addresses: $GRAFANA_SMTP_TO
          singleEmail: false

policies:
  - orgId: 1
    receiver: news-podcast-email
    group_by: [grafana_folder, alertname, service_name]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 30m

